
export const budget = [
    {date: '12 Nov, 2019', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '13 Dec, 2019', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '15 Jan, 2020', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '22 Feb, 2020', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 Mar, 2020', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 May, 2020', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 Jun, 2020', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 Apr, 2020', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 Jul, 2020', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 Oct, 2019', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 Sep, 2019', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
    {date: '12 Aug, 2019', items: [{desc: 'Fuel for the Marketers', rate: 5000, qty: 4, amount: 20000,},{desc: 'Fuel for the MD', rate: 8000, qty: 1, amount: 8000,},{desc: 'Toll Gate Payment', rate: 6000, qty: 4, amount: 24000,}]},
];


export const landlords = [
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
]


export const tenants = [
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
    {name: 'Modd Family', address: '12B Somewhere in, water coopperation road', email: 'modd.family@something.com', cp: 'Tobusun olamide', phone: '08162300796'},
]

export const accounts = [
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
    {name: "Modd Family", bank: 'Access Bank Plc', number: '0011223344', sc: 23455, owner: 'Modd Family'},
    {name: "Apapa Bulk Terminal", bank: 'Access Bank Plc', number: '0011225566', sc: 23455, owner: 'Olympic Towers'},
];


export const flats = [
    {flat: 'AM6', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',},
     {flat: 'AR6', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 4, baths: 3, park: 2, tenacy: "05/05/2020 - 05/04/2021",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'BR8', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 3, baths: 2, park: 1, tenacy: "05/05/2020 - 05/04/2021",note: 'Owing Rent for Six months'},
     {flat: 'BM4', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 4,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'BP10', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 2,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'AP11', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'AM6', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',},
     {flat: 'AR6', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 4, baths: 3, park: 2, tenacy: "05/05/2020 - 05/04/2021",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'BR8', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 3, baths: 2, park: 1, tenacy: "05/05/2020 - 05/04/2021",note: 'Owing Rent for Six months'},
     {flat: 'BM4', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 4,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'BP10', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 2,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'AP11', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'AM6', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',},
     {flat: 'AR6', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 4, baths: 3, park: 2, tenacy: "05/05/2020 - 05/04/2021",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'BR8', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 3, baths: 2, park: 1, tenacy: "05/05/2020 - 05/04/2021",note: 'Owing Rent for Six months'},
     {flat: 'BM4', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 4,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'BP10', property: 'Crestview Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 2,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Vacant', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
     {flat: 'AP11', property: 'Olympic Towers', address: '12B Somewhere in, Idowu martins, Victoria Island', beds: 3,furnished: 'No', rent: 15500000, charge: 5000000,
     landlord: "Modd Family", tenant: 'Flour mill', status: 'Occupied', toilet: 4, baths: 3, park: 2, tenacy: "",note: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'},
];


export const invoice = [
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1245-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BP10', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1334-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BM4', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AM6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'No'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1245-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BP10', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1334-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BM4', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AM6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'No'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1245-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BP10', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1334-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BM4', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AM6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'No'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1245-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BP10', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1334-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'BM4', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'No'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AM6', items: [{id: 1, type: 'rent', renewal: 'yes'},{id: 1, type: 'charges', renewal: 'yes'},],},
    {invNo: `INV-1234-01`, date: "20 Jul, 2020", recipient: 'Flour Mill', total: 20000000, flat: 'AR6', items: [{id: 1, type: 'rent', renewal: 'No'},{id: 1, type: 'charges', renewal: 'yes'},],},
];



export const bankaccounts = [
    {no: '0123344556', name: "Cortts Real", sc: 123456, balance: '100000000.00', type: 'physical', bank: 'Access Bank',},
    {no: '0123344346', name: "Cortts Limited", sc: 123456, balance: '10000000.00', type: 'physical', bank: 'Access Bank',},
    {no: '0123344556', name: "Cortts Real", sc: 123456, balance: '25600000.00', type: 'physical', bank: 'Zenith Bank',},
    {no: '0123344346', name: "Cortts Limited", sc: 123456, balance: '50000.00', type: 'physical', bank: 'Zenith Bank',},
];